name: ectf_build_server
services:
    ectf_build_server:
        container_name: ectf_build_server
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - "8888:8888"
            - "5555:5555"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - firmware:/root/mounts/firmware
            - build_out:/root/mounts/build_out
            - secrets:/root/mounts/secrets
            - ../scrape-bot/temp:/root/mounts/targets
volumes:
    firmware:
    build_out:
    secrets:
