name: build_server
services:
    build_server:
        container_name: build_server
        build:
            dockerfile: ./Dockerfile
            context: .
        ports:
            - "8124:8124"
            - "8131:8131"
            - "8125:8125"
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - firmware:/root/mounts/firmware
            - build_out:/root/mounts/build_out
            - secrets:/root/mounts/secrets
            - ../scrape-bot/temp:/root/mounts/targets
        networks:
            - infra
volumes:
    firmware:
    build_out:
    secrets:

networks:
    infra:
        external: true
